### ISSUE TITLE
Running the documented Docker Compose build throws an error

### ISSUE THREAD

**Issue by mpiorowski** [tursodatabase/libsql#1312]
Straight from docs:
```
version: "3"
services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:main
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
    #   - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld
 ```

Throws Error:
```
/usr/local/bin/docker-entrypoint.sh: line 18: SQLD_HTTP_AUTH: unbound variable
```
