### ISSUE TITLE
Namespaces not available in replica

### ISSUE THREAD

**Issue by ryands17** [tursodatabase/libsql#1804]
Hey folks,

I have a `docker-compose` setup as follows:

```yml
services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:e853d54
    volumes:
      - db_data:/var/lib/sqld
    ports:
      - 8080:8080
      - 8082:8082
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
      - SQLD_GRPC_LISTEN_ADDR=0.0.0.0:5001
      - RUST_LOG=debug
    command: [ 'sqld', '--db-path', '/var/lib/sqld/primary.sqld', '--admin-listen-addr', '0.0.0.0:8082', '--enable-namespaces' ]
  replica:
    image: ghcr.io/tursodatabase/libsql-server:e853d54
    volumes:
      - db_replica:/var/lib/sqld
    depends_on:
      - db
    ports:
      - '8081:8080'
    environment:
      - SQLD_NODE=replica
      - SQLD_PRIMARY_URL=http://db:5001
      - RUST_LOG=debug
volumes:
  db_data:
  db_replica:
```

Without namespaces, this setup works fine and everything is replicated to the replica instance. But as soon as I enable namespaces and create a new namespace via the Admin API, it's not available in the replica and only in the primary.

Is there something I'm missing in my compose file?

**Comment by pauchiner** [comment]
Hi @ryands17, one little question, how you managed to use the namespaces?

I have a docker container with almost the same configuration as you but without the replica enabled, and I created two namespaces with the Admin API.

But when I try connecting to them under the **http://localhost:PORT/dev/NAMESPACE** it fails.

Im only able to connect to the default namespace with http://localhost:PORT

**Comment by djalmajr** [comment]
> But I can't connect to the namespaces from a external sqlite client, (Dataflare, Drizzle Studio)

Same here... I would also like to know.

**Comment by hatemjaber** [comment]
I have been combing the documentation trying to find out how to protect the admin api opened up on whatever port... it doesn't seem to care about the auth token. I know you guys were trying to get the namespace working or how to access it etc... I use a vscode extension called `rest client` but you can adapt this to whatever you use for api calls:

```
@api=http://localhost:6080
@api_admin=http://localhost:8082
@api_token={{$dotenv VSCODE_DATABASE_AUTHENTICATION}}

POST {{api}}/v2/pipeline
Authorization: Bearer {{api_token}}

{
  "requests": [
    { "type": "execute", "stmt": { "sql": "SELECT 1 as one" } },
    { "type": "close" }
  ]
}

###

POST http://db1.db.sarna.dev:6080
Content-Type: application/json
Authorization: Bearer {{api_token}}

{
  "statements": [
    { "q": "SELECT 1 AS one" }
  ]
}

###

GET {{api}}/health
Authorization: Bearer {{api_token}}

###

GET {{api}}/dump
Authorization: Bearer {{api_token}}

###

GET {{api}}/version
Authorization: Bearer {{api_token}}

###

POST {{api_admin}}/v1/namespaces/db2/create
Content-Type: application/json

{}

###

DELETE {{api_admin}}/v1/namespaces/db2

###

POST {{api_admin}}/v1/namespaces/test/fork/test-db
Content-Type: application/json

{}
```

here's my docker...

```
sqld_primary:
  image: ghcr.io/tursodatabase/libsql-server:latest
  platform: linux/amd64
  container_name: sqld_primary
  hostname: sqld_primary
  command: ["/bin/sqld", "--enable-namespaces", "--admin-listen-addr", "0.0.0.0:8082"]
  ports:
    - "0.0.0.0:6080:8080"  # Expose primary on port 8080
    - "0.0.0.0:8082:8082"  # Expose admin on port 8082
  volumes:
    - ./.sqld/primary:/var/lib/sqld  # Persist primary DB on the host
  environment:
    - SQLD_NODE=primary
    - SQLD_HTTP_AUTH=turso:turso
```

If you run on apple silicon you need to keep the `platform: linux/amd64`, otherwise you can remove it. the docker compose config should get you up and running, I mount the volume to local disk for easy access, you can put it in a docker volume...

if you want to access the local setup as if you were hitting a separate subdomain for each db, add an entry to `/etc/hosts` or your hosts file on whatever system with this `127.0.0.1 *.db.sarna.dev`. this will allow you to create the namespace you created and hit that db directly. the only commands I found were to create, delete, and fork a namespace which all three work no problems. 

I hope this helps you guys figure out your specific issues. if you happen to know how to secure the admin endpoint that exposes namespaces please let me know. it's probably something that hsould be non-accessible to the outside world and should only be access on the local network, but it would be nice to figure that out for the sake of securing it.
