### ISSUE TITLE
Allow using both rusqlite and libsql in the same process

### ISSUE THREAD

**Issue by wyhaya** [tursodatabase/libsql#526]
```toml
[dependencies]
libsql = { git = "https://github.com/tursodatabase/libsql" }
rusqlite = { version = "0.29" }
```

### Run

```rust
fn test() {
    rusqlite::Connection::open_in_memory().unwrap();
    libsql::Database::open_in_memory().unwrap().connect().unwrap();
}
```
### Output
```
thread 'main' panicked at /Users/.../libsql-311658d335deb3b1/c9b60a1/libsql/src/local/database.rs:88:17:
assertion `left == right` failed: libsql was configured with an incorrect threading configuration and
                the api is not safe to use. Please check that no multi-thread options have
                been set. If nothing was configured then please open an issue at:
                https://github.com/libsql/libsql
  left: 21
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/tursodatabase/libsql/blob/c9b60a1c8ed47889f39e25b5d105130245cc1403/libsql/src/local/database.rs#L84-L103
